version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: "weekly"
      time: "06:00"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]
    cooldown:
      default-days: 3

  - package-ecosystem: "docker"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]
    cooldown:
      default-days: 3

  - package-ecosystem: "npm"
    directory: "/"
    multi-ecosystem-group: "dependencies"
    patterns: ["*"]
    cooldown:
      default-days: 3
