packages:
  - frontend
  - backend
  - e2e
ignorePnpmfile: true
blockExoticSubdeps: true
minimumReleaseAge: 2880 # 2 days
trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 5760 # 4 days
ignoreScripts: true
trustLockfile: true
publicHoistPattern:
  - "@shikijs/*"
allowBuilds:
  better-sqlite3: true
  integer: true
